# Generated by Django 3.2.3 on 2021-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_isbn', models.CharField(max_length=13)),
                ('book_author', models.CharField(max_length=255)),
                ('book_year_pub', models.PositiveSmallIntegerField()),
                ('book_publisher', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('book_title',),
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('book_isbn', models.CharField(max_length=13)),
                ('book_rating', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('book_isbn',),
            },
        ),
        migrations.AddIndex(
            model_name='bookrating',
            index=models.Index(fields=['book_isbn'], name='RootDir_boo_book_is_332a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrating',
            index=models.Index(fields=['user_id'], name='RootDir_boo_user_id_a050f5_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_title'], name='RootDir_boo_book_ti_cb1de4_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['book_author'], name='RootDir_boo_book_au_a6944e_idx'),
        ),
    ]
